### PR TITLE
update as per apache-spark/master and integrate changes

### PR DESCRIPTION
**Pull request by gvramana**
Author: Venkata Ramana G ramana.gollamudi@huawei.com

### CODE REVIEW

**Comment by yzhou2001** [comment]
This is a significant work, thanks very much for all of the efforts!

Just two questions/comments:

1) HBaseCatalog.scala, Line 282:   HBase Tables are not temporary tables and their meta data are persistent. So probably you want to change this value to "false"?

2) HBaseRelation.scala, Line 569: for the new "insert" method, I think our InsertValueIntoTableCommand (in hbaseCommands.scala) should use this method. In addition to having a single point access to the functionality, it'll also be covered by our automated tests.

Otherwise, the PR looks fine with me.

**Comment by yzhou2001** [comment]
Sorry for closing this by accident. Just reopened it and hope no bad consequence will result.

**Comment by gvramana** [comment]
@yzhou2001 : Fixed review comments, Please review the same
1) fixed show tables returning hbase as temporary table
2) Unified the insert into value and insert from select flow as per
datasource interface.
3) fixed null insert from select issue

**Comment by gvramana** [comment]
@yzhou2001 We can remove InsertIntoHBaseTable, as "insert into ... select ... from" this is now handled by datasource api strategy DataSourceStrategy.scala:75. This intern calls HbaseRelation.insert. I also has tested both "insert into ... values" and "insert into ... select .. from". Now both hit the flow HbaseRelation.insert

**Comment by yzhou2001** [comment]
All right. I'd appreciate if you can merge the PR into the repo. Thanks.

**Pull request merged**
